### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by hu-ping** [hanpfei/chromium-net-independent#1]
你好作者：
      安装你提供的方法，我在执行ninja -C out/Default/ cronet 的时候会会出现：/usr/bin/ld.gold: error: treating warnings as errors的错误。有劳作者指点。

**Comment by hanpfei** [comment]
从错误信息来看，似乎是用到了 host 的工具链，不过给 android 编译应该用的是交叉编译的工具链才对。
麻烦你提供一下，具体你是怎么做的。
把你的 out/Default/args.gn 文件贴一下看看。
此外，把编译时完整的 log 输出贴一下。

**Comment by hanpfei** [comment]
/usr/bin/ld.gold: error: treating warnings as errors
这样的报错，通常是由于链接时候的标志 '-Wl,--fatal-warnings' 引起的。

可以尝试如下的一些方法来解决：

方法一
在 out/Default/args.gn 中加入如下的一行：

```
fatal_linker_warnings = false
```

然后在项目根目录执行如下命令：

```
$ gn gen out/Default/
$ ninja -C out/Default/ cronet
$ ninja -C out/Default/ cronet_java
```

方法二
配置了 '-Wl,--fatal-warnings' 标志的地方主要有 `build/common.gypi` 和 `build/config/compiler/BUILD.gn`，可以把 `build/common.gypi` 文件中第 5016 行注释掉或移除。或者把这几个文件中出现的 '-Wl,--fatal-warnings' 标志全部注释掉或移除。

然后在项目根目录执行如下命令：

```
$ gn gen out/Default/
$ ninja -C out/Default/ cronet
$ ninja -C out/Default/ cronet_java
```

**Comment by hu-ping** [comment]
target_os = "android"
 target_cpu = "arm"  # (default)
 is_debug = false  # (default)
 
 # Other args you may want to set:
 is_component_build = false
 is_clang = false
 symbol_level = 1  # Faster build with fewer symbols. -g1 rather than -g2
 enable_incremental_javac = false  # Much faster; experimental
 android_ndk_root = "/home/huping/workspace/android/android-ndk-r10e"
 android_sdk_root = "/home/huping/workspace/android/android-sdk-linux"
 android_sdk_build_tools_version = "24"
 
 disable_file_support = true
 disable_ftp_support = true
 enable_websockets = false




你好，这时我的out/Default/args.gn

**Comment by hanpfei** [comment]
args.gn 文件看上去没有问题。
试一下前面给你贴的那些方法，看看能不能解决你的编译失败。

**Comment by hu-ping** [comment]
非常感谢作者，通过你的提示，顺利通过了编译。谢谢！
